### ISSUE TITLE
HA camera settings

### ISSUE THREAD

**Issue by Xitro01** [oischinger/eufyp2pstream#1]
Hi @oischinger,

I started using your addon, as there still isn't a clear answer on how to set it up correctly with all the add-ons and integrations that are needed. I installed this add-on and it seems to work instantly. It only takes a couple of seconds to start the stream, but seems to be much faster already.

Could you share the settings how to add this as a camera on HA? The image in your repo is missing.

Also, are automations to start the stream still needed? It seems as this add-on is taking care of that.

Would also be great to be able to add this as a repo in the add-ons of HA.

Thanks in advance!

**Comment by oischinger** [comment]
Hi @Xitro01 
Sorry for not providing better documentation.
Actually the whole thing isn't ready for prime time yet. But I'll improve the docs soon.

Note that I myself.am currently not using it as a camera in HA and I'm not sure if that's a good idea. I believe that HA will keep the Livestream open permanently which effectively disables motion detection.

That's far from ideal. Maybe the best solution is to have a camera that only shows snapshots updated every few minutes from the addon and when streaming one uses the web Interface directly. The benefit of that is that it will at some point also support talkback. I already implemented talkback from an ffmpeg stream but not yet from the webm microphone input.

**Comment by Xitro01** [comment]
> Hi @Xitro01 Sorry for not providing better documentation. Actually the whole thing isn't ready for prime time yet. But I'll improve the docs soon.
> 
> Note that I myself.am currently not using it as a camera in HA and I'm not sure if that's a good idea. I believe that HA will keep the Livestream open permanently which effectively disables motion detection.
> 
> That's far from ideal. Maybe the best solution is to have a camera that only shows snapshots updated every few minutes from the addon and when streaming one uses the web Interface directly. The benefit of that is that it will at some point also support talkback. I already implemented talkback from an ffmpeg stream but not yet from the webm microphone input.

Just a snapshot that is updated every few minutes is perfect. I would like to trigger (with a pop-up) the livestream only on a doorbell press. Currently I still don't have a working solution for that. Hopefully you can help me out, your add-on seems great, as you won't have to install a multitude of integrations and add-ons.

It's currently still installed, but I don't know how to call the camera view right now, I think I need to create a camera in HA for that as it is stated in your docs.

**Comment by oischinger** [comment]
I updated the README.MD. Should be straigth forward now.

Again. it may lead to issues because HA might be keeping the stream always alive

**Comment by Xitro01** [comment]
Actually works flawless now. Made some automations to turn the camera on and off so it won’t always stream.
The image shows up immediately. Only thing is that the stream is behind a good 5 seconds. Any idea how to make this gap to actually live view smaller?

**Comment by oischinger** [comment]
I guess that's due to home assistants streaming. If you use the webm custom component in Lovelace the delay is much lower.

Therefore I have my doubts that the home Assistant generic camera is very useful. It'll always be slower than webm

**Comment by Xitro01** [comment]
> I guess that's due to home assistants streaming. If you use the webm custom component in Lovelace the delay is much lower.
> 
> Therefore I have my doubts that the home Assistant generic camera is very useful. It'll always be slower than webm

Been googling that, but can’t find it. What custom component do you mean?

**Comment by oischinger** [comment]
https://github.com/AlexxIT/WebRTC

**Comment by Xitro01** [comment]
> https://github.com/AlexxIT/WebRTC

Ah, ofcourse. Will try to use that again, hopefully works this time.

**Comment by Xitro01** [comment]
> https://github.com/AlexxIT/WebRTC

This causes the distorted image again, not as often as it used to be. But it happens quite a lot. So I'm afraid I have to stick with the default HomeAssistant player and have quite a big delay.

**Comment by DerHerzog7** [comment]
I'm struggling to get the add on to work. I'm not sure if I'm still meant to be using the RTSP Simple Server add-on or if this is meant to replace it? Also, is it just meant to detect the stream or do I need to get the URL from somewhere?

**Comment by iraklis10** [comment]
> I'm not sure if I'm still meant to be using the RTSP Simple Server add-on or if this is meant to replace it? 
No need for any other add-on apart from eufy-security-ws.
> Also, is it just meant to detect the stream or do I need to get the URL from somewhere?
It creates the stream automatically if you click "open web ui" after installing

**Comment by oischinger** [comment]
I changed the way this addon works by not embedding go2rtc anymore. instead you'll have to install the go2rtc addon as well. Please see the readme
